binance_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bot.urls'))
]

bot/urls.py
from django.urls import path
from .views import AssetLIstView, AssetUpdateView, AssetCreateView

urlpatterns = [
    path('home/', AssetLIstView.as_view()),
    path('update/<int:pk>/', AssetUpdateView.as_view(), name='update'),
    path('create/', AssetCreateView.as_view(), name='create')
]

bot/models.py
from django.db import models 
from django.utils.translation import gettext_lazy as _ 
from bot.bin_logic import LIMIT, QUANTITY

STATUS = (
    ('OPEN', 'OPEN'),
    ('CLOSE', 'CLOSE'),
    ('ERROR', 'ERROR'),
)


class Asset(models.Model):
    """Модель актива для торговли"""
        
    name = models.CharField(verbose_name='название', max_length=255)
    product = models.CharField(max_length=20, default='BTCUSDT')
    limit = models.FloatField(verbose_name='граница изменения цены',
                                default=0)
    quantity = models.IntegerField(verbose_name='количество', default=0)
    price = models.FloatField(verbose_name='цена', default=0)
    status = models.CharField(choices=STATUS, max_length=10, default='OPEN')
    ma = models.FloatField(default=0)
    work = models.BooleanField(default=False)
    
    
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super(Asset, self).save(*args, **kwargs)
        LIMIT.value = self.limit
        QUANTITY.value = self.quantity
                
    class Meta:
        verbose_name = 'Актив'
        verbose_name_plural = 'Активы'

bot/views.py
from multiprocessing import Process
from django.http import Http404, JsonResponse
from django.views.generic import UpdateView, ListView, CreateView
from django.shortcuts import render
from bot.models import Asset

from bot.bin_logic import client, start_trade


class AssetLIstView(ListView):
    """ Клас отображения на главной странице """
    context_object_name = 'data'
    template_name = 'home.html'
    
    def get_queryset(self): #
        queryset = Asset.objects.filter(status='OPEN')
        for i in queryset:
            if not i.work:
                print('start')
                i.work = True
                i.save()
                Process(target=start_trade, args=[i], daemon=True).start()
        return queryset
                
    
    
class AssetUpdateView(UpdateView):
    """Обновляяет даные объекта"""
    model = Asset
    fields = ['limit', 'quantity']
    success_url = '/home'
    template_name = 'update.html'
    

class AssetCreateView(CreateView):
    """Создает объект asset"""
    model = Asset
    fields = ['name', 'limit', 'quantity']
    success_url = '/home'
    template_name = 'create.html'
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class=" mt-5 pt-5 container">
    {% block container %}
    {% endblock container %}
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</html>

templates/create.html
{% extends 'base.html' %}
{% block container %}
    
<form action="" method="post">
    {% csrf_token %}
    <table class="table">
        <thead>
          <tr>
            <th scope="col">NAME</th>
            <th scope="col">PRODUCT</th>
            <th scope="col">LIMIT</th>
            <th scope="col">QUANTITY</th>
            <th scope="col">PRICE</th>            
            <th scope="col">MA</th>
            <th scope="col">STATUS</th>
          </tr>
        </thead>
        <tbody>
            <td><input class="form-control" type="text" name="name" value=""  required id="id_name"></td>
            <td>BTCUSDT</td>
            <td><input class="form-control" type="number" name="limit" value="" step="1e-8" required id="id_limit"></td>
            <td><input class="form-control" type="number" name="quantity" value="" required id="id_quantity"></td>
            <td>0</td>
            <td>0</td>
            <td>OPEN</td>
        </tbody>
    </table>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock container %}

templates/home.html
{% extends 'base.html' %}
{% block container %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">NAME</th>
            <th scope="col">PRODUCT</th>
            <th scope="col">LIMIT</th>
            <th scope="col">QUANTITY</th>
            <th scope="col">PRICE</th>            
            <th scope="col">MA</th>
            <th scope="col">STATUS</th>
          </tr>
        </thead>
        <tbody>
            {% for i in data %}
              {% if i.status == 'CLOSE' %}
                  <tr style="background-color: rgb(206, 200, 200)">
              {% elif i.status == 'OPEN'%}
                  <tr style="background-color: rgb(74, 228, 74)">
              {% else %}
                  <tr style="background-color: rgb(223, 30, 30)"> 
              {% endif %}             
            <td>{{ i.name }}</td>
            <td>{{ i.product }}</td>
            <td>{{ i.limit }}</td>
            <td>{{ i.quantity }}</td>
            <td>{{ i.price }}</td>
            <td>{{ i.ma }}</td>
            <td>{{ i.status }}</td>
            <td><a href="{% url 'update' i.pk %}" style="color: black;">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16" >
                    <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
                  </svg>
            </a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      {% if not data %}
          <a href="{% url 'create' %}" class="btn btn-primary">Create</a>
      {% endif %}
{% endblock container %}

templates/update.html
{% extends 'base.html' %}
{% block container %}
    
<form action="" method="post">
    {% csrf_token %}
    <table class="table">
        <thead>
          <tr>
            <th scope="col">NAME</th>
            <th scope="col">PRODUCT</th>
            <th scope="col">LIMIT</th>
            <th scope="col">QUANTITY</th>
            <th scope="col">PRICE</th>            
            <th scope="col">MA</th>
            <th scope="col">STATUS</th>
          </tr>
        </thead>
        <tbody>
            <td>{{ object.name }}</td>
            <td>{{ object.product }}</td>
            <td><input class="form-control" type="number" name="limit" value="{{ object.limit }}" step="1e-8" required id="id_limit"></td>
            <td><input class="form-control" type="number" name="quantity" value="{{ object.quantity }}" required id="id_quantity"></td>
            <td>{{ object.price }}</td>
            <td>{{ object.ma }}</td>
            <td>{{ object.status }}</td>
        </tbody>
    </table>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock container %}